import Container from '../components/container'
import MoreStories from '../components/more-stories'
import HeroPost from '../components/hero-post'
import Intro from '../components/intro'
import Layout from '../components/layout'
import { getAllPostsForHome } from '../lib/api'
import { getHeroImageForHome } from '../lib/components/heroImage'
import { getTextWithDotPointsForHome } from '../lib/components/textWithDotPoints'
import { getTextContentsForHome } from '../lib/components/textContents'
import Head from 'next/head'
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';

export default function Index({ preview, heroImages, textWithDotPoints, textContents }) {
  const heroImage = heroImages[0]
  const textWithDotPoint = textWithDotPoints[0]
 
  return (
    <>
      <Layout preview={preview}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="ic-info">
          <header className="ic-info-header">
            <img
              src={heroImage.mobileImage.url}
              className="ic-info-banner ic-mobile-only"
            />
            <img
              src={heroImage.desktopImage.url}
              className="ic-info-banner ic-desktop-only"
            />
          </header>

          <div className="ic-info-grid">
            <div className="ic-info-section ic-info-section__what-is-ic">
              <h1>{textWithDotPoint.heading}</h1>

              <div className="ic-info-section-columns">
                <div className="ic-info-section-columns__column">
                  <div className="ic-info-section-copy">
                    { documentToReactComponents(textWithDotPoint.body.json) }
                  </div>

                  <div className="ic-desktop-only">
                    <a
                      href={textWithDotPoint.ctaUrl}
                      className="ic-button-solid ic-button-solid--arrow"
                      target="_blank"
                      rel="noopener"
                    >
                      { textWithDotPoint.ctaText }
                      <svg
                        width="14"
                        height="14"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path d="M7 .333 5.827 1.508l4.65 4.659H.334v1.666h10.142l-4.65 4.659L7 13.667 13.667 7 7.001.333Z"></path>
                      </svg>
                    </a>
                  </div>

                  <div className="ic-info-app-stores ic-mobile-only">
                    <a
                      href="https://onelink.to/hdsweq"
                      target="_blank"
                      rel="noopener"
                    >
                      <img
                        src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/app-store-button.svg"
                        alt="Download on the App Store"
                      />
                    </a>
                    <a
                      href="https://onelink.to/hdsweq"
                      target="_blank"
                      rel="noopener"
                    >
                      <img
                        height="48"
                        src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/google-play-button.png"
                        alt="Get it on Google Play"
                      />
                    </a>
                  </div>
                </div>
                <div className="ic-info-section-columns__column">
                  { documentToReactComponents(textWithDotPoint.dotPoints.json) }
                </div>
              </div>
            </div>
            <div className="ic-info-section ic-info-section__how-it-works">
              <h2>{ textContents[0].heading }</h2>
              { documentToReactComponents(textContents[0].body.json) }
            </div>
            <div className="ic-info-section ic-info-section__our-doctors">
              <h2>{ textContents[1].heading }</h2>
              <div className="ic-info-section-copy">
                { documentToReactComponents(textContents[1].body.json) }
              </div>
            </div>
            <div className="ic-info-section ic-info-section__faq">
              <h2>Frequently Asked Questions</h2>

              <div className="ic-info-section-columns">
                <div className="ic-info-section-columns__column">
                  <div className="ic-info-section-copy">
                    <p>
                      Here you will find some frequently asked questions about
                      Instant Consult.
                    </p>
                  </div>

                  <div className="ic-faq">
                    <details>
                      <summary>
                        What is Instant Consult
                        <svg
                          width="12"
                          height="8"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M1.41.551 6 5.131l4.59-4.58L12 1.961l-6 6-6-6L1.41.551Z"></path>
                        </svg>
                      </summary>
                      <div className="ic-faq__answer">
                        <p>
                          Instant Consult provides you with the ability to have a
                          health consultation with an Australian registered, fully
                          qualified and experienced Doctor via video call,
                          anywhere in Australia.
                        </p>
                        <p>
                          They provide a platform for affordable consultations
                          from the comfort of your home or wherever you are. No
                          need to book an appointment - simply “Request a Consult”
                          and the first available Doctor will connect with you
                          instantly, usually in less than 15 minutes. If you would
                          prefer, you can also book an appointment time for the
                          Doctor to call you back at no extra charge.
                        </p>
                        <p>
                          Doctors are available to answer your questions 7 days a
                          week 6am-midnight (AEST)
                        </p>
                        <p>
                          Consultation costs are extremely competitive and do not
                          increase outside normal office hours or on weekends or
                          public holidays.
                        </p>
                      </div>
                    </details>
                    <details>
                      <summary>
                        What can I use Instant Consult for?
                        <svg
                          width="12"
                          height="8"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M1.41.551 6 5.131l4.59-4.58L12 1.961l-6 6-6-6L1.41.551Z"></path>
                        </svg>
                      </summary>
                      <div className="ic-faq__answer">
                        <p>
                          Instant Consult doctors can provide prescriptions
                          (including Repeats), specialist referrals, medical
                          certificates and pathology and radiology requests. You
                          can also speak to their doctors for just about any
                          general medical issue, including cold and flu, sore
                          throat, sexual health, diarrhoea, vomiting and more.
                          Suitable medical consultations can be effectively
                          managed online via video call. Using Instant Consult
                          takes pressure off medical practices as well as hospital
                          emergency departments, letting their local doctors and
                          nurses focus on physical examination and genuine
                          emergency care.
                        </p>
                      </div>
                    </details>
                    <details>
                      <summary>
                        Should I use Instant Consult in cases of emergency?
                        <svg
                          width="12"
                          height="8"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M1.41.551 6 5.131l4.59-4.58L12 1.961l-6 6-6-6L1.41.551Z"></path>
                        </svg>
                      </summary>
                      <div className="ic-faq__answer">
                        <p>
                          No, if you need emergency medical attention in Australia
                          please dial 000. Examples of medical emergencies
                          include: chest pain, head or spinal injuries, severe
                          bleeding, loss of movement, breathing difficulties and
                          reduced level of consciousness.
                        </p>
                      </div>
                    </details>
                  </div>

                  <div className="ic-info-section-copy ic-info-section__faq-note">
                    <p>
                      If the information above doesn't answer your query or
                      concern, please feel free to view all Frequently Asked
                      Questions on the Instant Consult website or contact the
                      Instant Consult support team on
                      <a href="mailto:support@instantconsult.com.au">
                        support@instantconsult.com.au
                      </a>
                      .
                    </p>
                  </div>

                  <div className="ic-info-faq-footer">
                    <a
                      href="https://www.instantconsult.com.au/faq/"
                      className="ic-button-outline"
                      target="_blank"
                      rel="noopener"
                    >
                      <span>
                        <span className="ic-desktop-only--inline">View</span> all
                        Frequently Asked Questions
                      </span>
                      <svg
                        width="14"
                        height="14"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path d="M7 .333 5.827 1.508l4.65 4.659H.334v1.666h10.142l-4.65 4.659L7 13.667 13.667 7 7.001.333Z"></path>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="ic-info-section ic-info-section__speak-to-doctor">
              <h2>Speak to a Doctor Today</h2>

              <div className="ic-info-section-copy">
                <p>
                  Instant Consult makes it easy to get access to fully qualified
                  online doctors in Australia at your convenience - no matter
                  where you are in Australia. Our doctors are all Australian
                  Registered GPs, so you know you are in safe, competent hands.
                </p>
              </div>

              <div className="ic-desktop-only">
                <a
                  href="https://onelink.to/hdsweq"
                  className="ic-button-solid ic-button-solid--arrow"
                  target="_blank"
                  rel="noopener"
                >
                  Get Started
                  <svg width="14" height="14" xmlns="http://www.w3.org/2000/svg">
                    <path d="M7 .333 5.827 1.508l4.65 4.659H.334v1.666h10.142l-4.65 4.659L7 13.667 13.667 7 7.001.333Z"></path>
                  </svg>
                </a>
              </div>

              <div className="ic-info-app-stores ic-mobile-only">
                <a
                  href="https://onelink.to/hdsweq"
                  target="_blank"
                  rel="noopener"
                >
                  <img
                    src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/app-store-button.svg"
                    alt="Download on the App Store"
                  />
                </a>
                <a
                  href="https://onelink.to/hdsweq"
                  target="_blank"
                  rel="noopener"
                >
                  <img
                    height="48"
                    src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/google-play-button.png"
                    alt="Get it on Google Play"
                  />
                </a>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  )
}

export async function getStaticProps({ preview = false }) {
  const heroImages = (await getHeroImageForHome(preview)) ?? []
  const textWithDotPoints = (await getTextWithDotPointsForHome(preview)) ?? []
  const textContents = (await getTextContentsForHome(preview)) ?? []
  debugger
  return {
    props: { preview, heroImages, textWithDotPoints, textContents },
  }
}
